# Generated by Django 3.2.19 on 2023-05-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='content',
            new_name='about',
        ),
    ]
