# Generated by Django 3.2.19 on 2023-05-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pettales', '0003_alter_pettale_image'),
        ('petpics', '0003_alter_petpic_image'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pet_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petpics.petpic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pet_tale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pettales.pettale'),
        ),
    ]
