# Generated by Django 3.2.19 on 2023-06-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pettales', '0004_pettale_tldr'),
        ('petpics', '0003_alter_petpic_image'),
        ('comments', '0003_remove_comment_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pet_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petpics.petpic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pet_tale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pettales.pettale'),
        ),
    ]
