# Generated by Django 3.2.19 on 2023-06-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('comments', '0004_auto_20230601_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
    ]
