# Generated by Django 3.2.19 on 2023-06-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='followed_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='followed_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='pets.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'followed_owner', 'followed_pet')},
        ),
        migrations.RemoveField(
            model_name='follower',
            name='followed',
        ),
    ]
