# Generated by Django 3.2.19 on 2023-06-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0004_auto_20230603_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_owner', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'followed_owner')},
            },
        ),
        migrations.CreateModel(
            name='PetFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_pet', to='pets.pet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'followed_pet')},
            },
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
