# Generated by Django 3.2.19 on 2023-05-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('pettales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettale',
            name='name',
        ),
        migrations.AddField(
            model_name='pettale',
            name='pet',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
            preserve_default=False,
        ),
    ]
