# Generated by Django 3.2.19 on 2023-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettales', '0002_auto_20230517_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettale',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_htulnf', upload_to='images/'),
        ),
    ]
