# Generated by Django 3.2.19 on 2023-05-26 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pettales', '0003_alter_pettale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettale',
            name='tldr',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
