# Generated by Django 3.2.19 on 2023-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpics', '0002_auto_20230517_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpic',
            name='image',
            field=models.ImageField(default='../default_post_htulnf', upload_to='images/'),
        ),
    ]
